eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka
spring.datasource.url=jdbc:h2:mem:testdb1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=rohiest
spring.datasource.password=roht
spring.h2.console.enabled=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto = update
